services:
  aispreadsheet-frontend:
    depends_on:
      - aispreadsheet-backend
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  aispreadsheet-backend:
    depends_on:
      - db
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./python-backend/.env
    
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aispreadsheet
